name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          node-version: '20'

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Generate Docker tags
        uses: docker/metadata-action@v3
        with: 
          images: docker.io/mishkafloof/Dockerfile
          tags: |
            latest
            ${{ github.ref }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mishkafloof/project4
          tag_with_ref: true
